# Documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          minor-and-patch:
              applies-to: version-updates
              update-types:
                  - 'minor'
                  - 'patch'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          minor-and-patch:
              applies-to: version-updates
              update-types:
                  - 'minor'
                  - 'patch'
