[build]
buildCommand = 'npx nx run rockket-backend:build:production'

[environments.production.deploy]
preDeployCommand = [
    'DATABASE_URL=$DATABASE_BASE_URL/prod npx nx run rockket-backend:db:migrate:deploy',
]
startCommand = 'DATABASE_URL=$DATABASE_BASE_URL/prod npx nx run rockket-backend:serve-production'

[environments.Staging.deploy]
preDeployCommand = [
    'DATABASE_URL=$DATABASE_BASE_URL/main npx nx run rockket-backend:db:migrate:deploy',
]
startCommand = 'DATABASE_URL=$DATABASE_BASE_URL/main npx nx run rockket-backend:serve-production'

[environments.pr.deploy]
preDeployCommand = [
    'DATABASE_URL=$DATABASE_BASE_URL/pr-$(bash ../scripts/get-pull-number-from-branch.sh $RAILWAY_GIT_BRANCH) npx nx run rockket-backend:db:migrate:deploy',
]
startCommand = 'DATABASE_URL=$DATABASE_BASE_URL/pr-$(bash ../scripts/get-pull-number-from-branch.sh $RAILWAY_GIT_BRANCH) npx nx run rockket-backend:serve-production'
