BEGIN;
ALTER TYPE "TaskPriority" RENAME VALUE 'Urgent' TO 'URGENT';
ALTER TYPE "TaskPriority" RENAME VALUE 'High' TO 'HIGH';
ALTER TYPE "TaskPriority" RENAME VALUE 'Medium' TO 'MEDIUM';
ALTER TYPE "TaskPriority" RENAME VALUE 'None' TO 'NONE';
ALTER TYPE "TaskPriority" ADD VALUE 'LOW';
ALTER TYPE "TaskPriority" RENAME VALUE 'Optional' TO 'OPTIONAL';

ALTER TYPE "TaskStatus" RENAME VALUE 'In_Progress' TO 'IN_PROGRESS';
ALTER TYPE "TaskStatus" ADD VALUE 'IN_REVIEW';
ALTER TYPE "TaskStatus" RENAME VALUE 'Open' TO 'OPEN';
ALTER TYPE "TaskStatus" RENAME VALUE 'Backlog' TO 'BACKLOG';
ALTER TYPE "TaskStatus" RENAME VALUE 'Completed' TO 'COMPLETED';
ALTER TYPE "TaskStatus" RENAME VALUE 'Not_Planned' TO 'DISCARDED';
COMMIT;